name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: omk4r72
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#84a0c6,#4b6992,#1e3658
